package sample.entity;
// Generated 20-Oct-2016 10:32:37 AM by Hibernate Tools 4.3.1



/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private String makh;
     private String username;
     private String password;
     private String hoten;
     private boolean gioitinh;
     private String email;
     private String sodt;

    public Customers() {
    }

    public Customers(String makh, String username, String password, String hoten, boolean gioitinh, String email, String sodt) {
       this.makh = makh;
       this.username = username;
       this.password = password;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.email = email;
       this.sodt = sodt;
    }
   
    public String getMakh() {
        return this.makh;
    }
    
    public void setMakh(String makh) {
        this.makh = makh;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public boolean isGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(boolean gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSodt() {
        return this.sodt;
    }
    
    public void setSodt(String sodt) {
        this.sodt = sodt;
    }




}


